tickets_app/urls.py
from django.urls import path

from tickets_app.views import home, all_tickets, tickets_details, use_ticket, create_tickets, assign_ticket, \
    unassigned_tickets

urlpatterns = [
    path('', home, name='home'),
    path('tickets/', all_tickets, name='all'),
    path('details/<str:ticket_id>/', tickets_details, name='details'),
    path('use/<str:ticket_id>', use_ticket, name='use'),
    path('create/', create_tickets, name='create'),
    path('assign/<str:ticket_id>/<int:user_id>', assign_ticket, name='assign'),
    path('unassigned/', unassigned_tickets, name='unassigned')

]

tickets_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tickets/', include('tickets_app.urls')),
    path('accounts/', include('user_management.urls')),

]

tickets_app/models.py
# Create your models here.
import uuid

from django.db import models

from tickets_project import settings


class Tickets(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    ticket_date = models.DateTimeField()
    status = models.CharField(max_length=50, default='Not Used')
    finish_date = models.DateTimeField()
    last_used = models.DateTimeField(null=True, blank=True)
    type_ticket = models.CharField(max_length=50, default='Day')

    def __str__(self):
        return f"Ticket UUID: {self.uuid}, Title: {self.title}, Status: {self.status}"


    class Meta:
        ordering = ['-ticket_date']

templates/tickets/all.html
{% extends "base.html" %}

{% block title %}Historial de Tickets{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h2 class="mb-4">Mis Tickets</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    {% if request.user.is_superuser %}
                        <th scope="col">Usuario</th>
                        <th scope="col">UUID</th>
                    {% endif %}
                    <th scope="col">Título</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Fecha de Ticket</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in tickets %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    {% if request.user.is_superuser %}
                        <td>{{ ticket.user.username }}</td>
                        <td>{{ ticket.uuid }}</td>
                    {% endif %}
                    <td>{{ ticket.title }}</td>
                    <td>{{ ticket.description }}</td>
                    <td>{{ ticket.ticket_date }}</td>
                    <td>{{ ticket.status }}</td>
                    <td>
                        <!-- Enlace a la página de detalles con el ID del ticket como parámetro -->
                        <a href="{% url 'details' ticket.uuid %}" class="btn btn-sm btn-primary">Detalles</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'home' %}" class="btn btn-primary">Volver al Inicio</a>
    </div>
</div>
{% endblock %}

templates/tickets/create.html
{% extends "base.html" %}

{% block title %}Creación de Tickets{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">Create Ticket</div>
                    <div class="card-body">
                        <form method="post" class="ticket-form">
                            {% csrf_token %}
                            {% if form.errors %}
                                <div class="alert alert-danger">
                                    <strong>Error:</strong> Please correct the following errors.
                                </div>
                            {% endif %}
                            <div class="form-group">
                                <label for="num_tickets">Number of tickets: </label><input class="form-control" name="num_tickets"
                                                                        id="num_tickets" type="text"
                                                                        value="{{ form.name.value }}">
                            </div>
                            <div class="form-group">
                                <label for="{{ form.title.id_for_label }}">Title:</label>
                                {{ form.title }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.description.id_for_label }}">Description:</label>
                                {{ form.description }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.ticket_date.id_for_label }}">Ticket Date:</label>
                                {{ form.ticket_date }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.status.id_for_label }}">Status:</label>
                                {{ form.status }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.finish_date.id_for_label }}">Finish Date:</label>
                                {{ form.finish_date }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.type_ticket.id_for_label }}">Type Ticket:</label>
                                {{ form.type_ticket }}
                            </div>
                            <button type="submit" class="btn btn-primary">Create Ticket</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_ticket_date").datepicker();
            $("#id_finish_date").datepicker();
        });
    </script>
{% endblock %}

templates/tickets/details.html
{% extends "base.html" %}

{% block title %}Detalles de Ticket{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="mb-4">Detalles de Ticket</h2>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Título:</h5>
                    <p class="card-text">{{ ticket.title }}</p>
                </div>
            </div>
            {% if request.user.is_superuser %}
                <div class="card mt-3">
                    <div class="card-body">
                        <h5 class="card-title">Usuario:</h5>
                        {% if ticket.user.username %}
                            <p class="card-text">{{ ticket.user.username }}</p>
                        {% else %}
                            <p class="card-text">No asignado</p>
                        {% endif %}
                    </div>
                </div>
                <div class="card mt-3">
                    <div class="card-body">
                        <h5 class="card-title">UUID:</h5>
                        <p class="card-text" id="uuid">{{ ticket.uuid }}</p>
                    </div>
                </div>
            {% endif %}
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Estado:</h5>
                    <p class="card-text">{{ ticket.status }}</p>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Fecha de Ticket:</h5>
                    <p class="card-text">{{ ticket.ticket_date }}</p>
                </div>
            </div>
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Fecha de Finalización:</h5>
                    <p class="card-text">{{ ticket.finish_date }}</p>
                </div>
            </div>
            {% if ticket.status == 'Not Used' and ticket.user != None %}
                <img src="data:image/png;base64,{{ qrcode }}" alt="Código QR">
            {% endif %}
            {% if request.user.is_superuser and ticket.user == None %}
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">Asignar Ticket</div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="user">Usuario</label>
                                        <select class="form-control" id="user" name="user">
                                            {% for user in users %}
                                                <option value="{{ user.id }}">{{ user.username }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <a id="user-link" href="#" class="btn btn-primary mt-3">Enlace</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            <a href="{% url 'all' %}" class="btn btn-primary mt-3">Volver a la Lista</a>
        </div>
    </div>
{% endblock %}

{% block scripts %}

    <script>
        // Obtener el elemento select y el enlace
        const select = document.getElementById('user');
        const link = document.getElementById('user-link');

        // Escuchar el evento de cambio en el select
        select.addEventListener('change', function () {
            // Obtener el valor seleccionado
            const selectedValue = select.value;
            const uuid = document.getElementById('uuid').innerHTML;
            // Actualizar el atributo href del enlace con el valor seleccionado
            console.log(selectedValue)
            link.href = '/tickets/assign/' + uuid + '/' + selectedValue;
        });
    </script>

{% endblock %}

templates/tickets/home.html
{% extends "base.html" %}

{% block title %}Tickets{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="mb-4">Solicitar Ticket</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="ticket_id">UUID del Ticket:</label>
                <input type="text" class="form-control" id="ticket_id" name="ticket_id" required>
            </div>
            <button type="submit" class="btn btn-primary">Solicitar</button>
        </form>
    </div>
</div>
{% endblock %}